metadata.json

Updated to 3.16 and works just fine

Add GNOME 3.16 to supported versions

---

metadata.json

Had a quick click around - everything seems to work fine. No errors logged in LookingGlass.

Add support for Gnome 3.20

---

AUTHORS.rst

[#136] Add Frederic to project leads.

---

data/metadata.json

[#154] Add Gnome-Shell 3.22 compability

---

README.rst

[#195] Provide details on development environment

---

extension/stuff.js

[#149] stuff.js: Remove obsolete 'parseFactString'

---

extension/stuff.js

[#203] stuff.js: Change formatDuration format

---

README.rst

The README.rst should be in sync with data/metadata.json
Closes: #209

[#209] Use correct UUDI in 'README.rst'

---

README.rst
data/metadata.json

Note: This used to be part of #215 
Closes #220

Update supported shell-version 3.26

---

Makefile

[#216] Makefile: Update to new 'convenience.js' location for 'collect'

---

Makefile

[#227] Makefile: Add 'test-style' target

---

extension/extension.js
extension/prefs.js
extension/stuff.js
extension/stylesheet.css
extension/widgets/categoryTotalsWidget.js
extension/widgets/factsBox.js
extension/widgets/ongoingFactEntry.js
extension/widgets/panelWidget.js
extension/widgets/todaysFactsWidget.js

[#232] Update copyright boilerplate to 2018

---

README.rst

- Add call for testers
- Add very basic usage information
- Remove news of Frederic as new maintainer
Closes: #233 #158

[#158][#233] Update Readme

---

extension/extension.js

This fixes gnome-shell freezes under Wayland (at least in Fedora), as it
seems that it stalls gnome-shells main loop. fixes #159

Use asynchronous DBus proxy creation

---

Makefile

This was originally part of PR #215 
Also:
- Fix typo
Closes #222

[#222] Seriallize 'clean-build' and 'collect' make targets

---

README.rst

Not sure if it was an intentional pun or a typo. 
Feel free to decline this PR :)

Fix typo in README.

---

data/metadata.json

[#250] Document compatibility with GNOME Shell 3.28

---

docs/hacking.rst

[#237] Add additional reference to the hacking section

---

data/locale/messages.pot

[#264] Add 'messages.pot' to repository.

---

README.rst

[#268] Bump latest supported shell version in README

---

Makefile

[#274] Improve/Fix dependencies for 'compile' and 'dist' targets
