extension.js
In Gnome 3.16, the extension actually loads with an error because the API changed from Shell.KeyBindingMode to Shell.ActionMode.
This fixes it.
=> Update to Gnome 3.16 API

extension/metadata.json
Instead of an incrementing build number we use [semantic
versioning](http://semver.org) from now on. Starting at ``0.10.0``.
As far as I am able to figure from the non existing documentation of
``metadata.json`` keys there are no particular contrains on the version
string, so this switch should be trivial.
Closes: #117
=> [#117] Switch to semantic versioning

AUTHORS.rst
This PR adds a listing of all contributors so far. Future contributors should add themselfs here, which should be pointed out in the *contribution guidelines*.
We separated contributors up to today as 'original authors/contributors' in order to provide a clear cut for any potential upcoming refactoring that may be required and to be as transparent as possible.
Closes: #127
=> [#127] Add Contibutor listing

extension.js
* Set a style on input search following theme style
Fixes #103
=> [#103] Provide a generic class on search input

CONTRIBUTING.rst, README.rst, docs/hacking.rst, docs/index.rst, docs/packaging.rst, docs/styleguide.rst, docs/versioning.rst
This PR expands what little documentation we already had and adds several new pages to help potential contributors to get a quick overview about how things work as well as to codify best practices via the *Styleguide*.
I opted to use a single commit for each documentation page to be more verbose and transparent. If you @border0464111 feel that this is too much, please let me know.
=> [133] Provide Basic Documentation

Makefile
Our `dist` target now also create a tarball of the extension that can
be extracted right into `~/.local/share/gnome-shell/extensions/` if we
want to install the extension manually and not via
`extensions.gnome.org`.
This avoids people clone the repository itself as done previously, which
would not work anymore anyways as the new structure does not match what
gnome shell extensions should look like.
Those new tarballs should be discributed as primary releases on github
in order to complement `extensions.gnome.org`.
Closes: #127
=> [#127] Improve 'dist' target to create tarball

.editorconfig, extension/extension.js, extension/stuff.js, extension/widgets/categoryTotalsWidget.js, extension/widgets/factsBox.js, extension/widgets/ongoingFactEntry.js, extension/widgets/panelWidget.js, extension/widgets/todaysFactsWidget.js
This commit provides a major reorganization and refactoring of our main
codebase. In general three main objectives are persued in this.
1. Instead of few extensive functions with intransparent shared state
and monkey patching we try to split our codebase into various decoupled
objects. The main idea is to split up each individual "widget" into its
own proper class and have it handle all but only the logic it is really
concerned with. This has several benefits. For one it is far more
transparent which parameters are relevant to the widget. Secondly: if we
need to have some sort of state it is confined to the widget that
actually needs it. Third: All logic happens right where it is relevant.
That should make the code much more maintainable as contributors do not
have to browse thorugh the …
=> General refactoring and restructuring

README.rst
Under the new setup, installation via symlinking is no longer possible.
This commit provides new instructions on how to setup hamster from ``develop``.
Closes: #193
=> [#193] Update instructions for manual installation

README.rst
Doe to the cleaned up build process it is no longer possible to simply link to the repository in order to "install" the extension.
This PR includes basic documentation on how to "build" and install straight from the repository under the new system.
=> Update manual installation instruction in readme

README.rst, data/metadata.json
This updates the metadata to claim gnome-shell 3.22 and 2.24 as supported versions.
Closes: #172
=> [#172] Update supported shell versions

extension/extension.js, extension/stuff.js
This PR uses ``Gio.bus_watch_name`` to make sure
appearing/vanishing hamster dbus services are handled accordingly.
Right now we only act on vanishing/not running services by triggering
``disable``. Future itteration could consider being a bit more
forgiving, but for now this should help to make potential issues
attributed to the extension that are really caused by the dbus service
more clear.
Closes: #62
=> [#62] Ensure dbus services are present

extension/widgets/panelWidget.js
This widget installs a GSourceFunc to be triggered on a 60 seconds timeout
but it does not explicitly return GLib.SOURCE_CONTINUE in the callback,
meaning that the source will be removed after it gets called once, leaving
the label outdated forever.
This fixes this problem by explicitly returning GLib.SOURCE_CONTINUE there.
https://github.com/projecthamster/hamster-shell-extension/issues/189
=> Fix automatic refresh of the panel widget

extension/stuff.js
This PR does two things:
1. In order to allow a more accurate computation and representation of
fact-durations we no longer convert the retrieved seconds to minutes when
converting the retrieved dbus-fact.
2. We refactor our helper functions that are in charge of formatting
fact duration to various string representations. Besides cleaning up the
code we also provide proper docstrings that make parameters and expected
return values/formatting more transparent
Ref: #94
=> [#94] Refactor durartion handling

extension/extension.js
I was getting following error:
```
Extension "contact@projecthamster.org" had error: SyntaxError: redeclaration of let dbus_watcher
```
This patch fixes it.
=> [#210] Assign watcher for 'hamster-window-service' to its own variable.

Makefile, extension/extension.js, extension/widgets/categoryTotalsWidget.js, extension/widgets/factsBox.js, extension/widgets/ongoingFactEntry.js, extension/widgets/panelWidget.js, extension/widgets/todaysFactsWidget.js
This PR is a direct copy of Raphaël Hertzog work (#217 ) with just minor (mostly markdown related) changes to commit messages.
This PR does tree things:
- Avoid creation of duplicated convinience.js files
- Use ``var`` instead of ``const`` to export variables
- Fix broken argument list for ``Gio.bus_watch_name()``
In effect this seems to fix several outstanding bugs.
For the original PR message and further information please refer to #217 
Fixes #205 #198
=> [#198][#205] Minor syntax fixes, Improved Makefile

README.rst
It's more secure that unencrypted git protocol.
=> Use https for git clone

extension/stuff.js
This commit makes sure fractions of full hours are returned as
specified.
Ref.: #224
=> [#224] Fix hour-fraction bit in 'formatDurationHours'

extension/widgets/todaysFactsWidget.js
The crashes that I have been experiencing all have backtraces leading
back to the "refresh" event and error messages explaining that we are
trying to use objects that have been destroyed.
This is the only place where we are destroying objects explicitly
instead of relying on the garbage collector. To fix the crash, I'm
simply using the `remove_all_children()` method instead of the
`destroy_all_children()` one.
Fixes #212
=> [#212] Avoid crashes due to accessing destroyed objects

extension/extension.js
Sorry for the late discovery. :(
I'm not sure if it fixes anything important, but at least fixes some warnings and prevents deferred_enable() to be called multiple times after disable/enable.
Closes: #240
=> [#240] Clear apiProxy & windowsProxy on disable()

.travis.yml
This basic CI setup simply fetches ``jshint`` via ``npm`` and runs the
style checks.
Closes: #228
=> [#228] Add basic style checks on CI setup

data/metadata.json, extension/extension.js, extension/widgets/factsBox.js, extension/widgets/ongoingFactEntry.js, extension/widgets/panelWidget.js
This was inspired by how it's done in gnome-shell-extensions for
[the places-menu for example](https://github.com/GNOME/gnome-shell-extensions/blob/master/extensions/places-menu/extension.js#L14).
Fixes #218
=> [#218] Fix broken localization

Makefile, data/locale/cs/LC_MESSAGES/hamster-shell-extension.po, data/locale/de/LC_MESSAGES/hamster-shell-extension.po, data/locale/es/LC_MESSAGES/hamster-shell-extension.po, data/locale/fr/LC_MESSAGES/hamster-shell-extension.po, data/locale/nl/LC_MESSAGES/hamster-shell-extension.po, data/locale/pl/LC_MESSAGES/hamster-shell-extension.po, data/locale/pt-BR/LC_MESSAGES/hamster-shell-extension.po, data/locale/ru/LC_MESSAGES/hamster-shell-extension.po
Provide a dedicated `gettext-catalogue` make target to generate an up to date gettext catalogue (`po`) file.
Closes: #253
=> [#253] Improve i18n generation

.travis.yml
As building and testing the docs is depend on several python packaged, we change the travis setup accordingly.
Closes: #255
=> [#255] Add 'test-docs' to CI
